# Default Processing Settings
defaults:
  max_emails: 2
  days_old: 2
  dry_run: true
  use_full_content: false
  llm_provider: "openai"  # default provider
  llm_model: "gpt-4o-mini"  # default model

# LLM Models Configuration
llm_providers:
  openai:
    models: 
      - "gpt-4o-mini"
      - "gpt-4o"
  bedrock:
    models:
      - "claude-sonnet-35"
      - "claude-haiku-35"
  ollama:
    models:
      - "llama-33-70B"
      - "deepseek-r1:7b"

# Email Labels
email_labels:
  - Financials
  - Personal
  - Utilities
  - Wellness
  - Shopping
  - Work
  - Misc
